### ISSUE TITLE
How to implement another collection ie author

### ISSUE THREAD

**Issue by donPuerto** [ldiebold/vue-remark-tutorial#3]
I'm having trouble implementing two references for Post. Ie tags and authors

**Comment by ldiebold** [comment]
It's been a while since I've used gridsome, but will have a quick look now for you :)

**Comment by ldiebold** [comment]
Just pushed some changes to this repo demonstrating a post with multiple authors :smile:

I filmed the whole thing, so [checkout it out](https://youtu.be/_oblY2elypc) if you want more guidance!

**Comment by donPuerto** [comment]
@ldiebold that so quick. Thanks mate. By the way i love your accent very crisp and clear, its like im using bose speaker.
